defaults: &defaults
      working_directory: ~/hig
      docker:
        - image: circleci/node:8.2.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Get vanilla node_modules for this revision of vanilla/package.json
      - restore_cache:
          key: dependency-cache-vanilla-v1-{{ checksum "src/implementations/vanilla/package.json" }}
      - run:
          name: npm Install (Vanilla)
          command: npm install
          working_directory: src/implementations/vanilla
      # Store vanilla node_modules for this revision of vanilla/package.json
      - save_cache:
          key: dependency-cache-vanilla-v1-{{ checksum "src/implementations/vanilla/package.json" }}
          paths:
            - src/implementations/vanilla/node_modules
      # Get React node_modules for this revision of react/package.json
      - restore_cache:
          key: dependency-cache-react-v1-{{ checksum "src/implementations/react/package.json" }}
      - run:
          name: npm Install (React)
          command: npm install
          working_directory: src/implementations/react
      # Store React node_modules for this revision of react/package.json
      - save_cache:
          key: dependency-cache-react-v1-{{ checksum "src/implementations/react/package.json" }}
          paths:
            - src/implementations/react/node_modules
      - run:
          name: Build (Vanilla)
          command: npm run lib
          working_directory: src/implementations/vanilla
      # Store vanilla build files for this commit
      - save_cache:
          key: lib-cache-vanilla-v1-{{ .Revision }}
          paths:
            - src/implementations/vanilla/lib
      - run:
          name: Build (React)
          command: npm run lib
          working_directory: src/implementations/react
      # Store React build files for this commit
      - save_cache:
          key: lib-cache-react-v1-{{ .Revision }}
          paths:
            - src/implementations/react/lib
  test:
    <<: *defaults
    steps:
      - checkout
      # Get vanilla node_modules for this revision of vanilla/package.json
      - restore_cache:
          key: dependency-cache-vanilla-v1-{{ checksum "src/implementations/vanilla/package.json" }}
      # Get vanilla build files for this commit
      - restore_cache:
          key: lib-cache-vanilla-v1-{{ .Revision }}
      - run:
          name: Start Server (Vanilla)
          command: ./node_modules/http-server/bin/http-server
          background: true
          working_directory: src/implementations/vanilla
      - run:
          name: Run Tests (Vanilla)
          command: npm run gemini-ci
          working_directory: src/implementations/vanilla
      # Get React node_modules for this revision of react/package.json
      - restore_cache:
          key: dependency-cache-react-v1-{{ checksum "src/implementations/react/package.json" }}
      # Get React build files for this commit
      - restore_cache:
          key: lib-cache-react-v1-{{ .Revision }}
      - run:
          name: Run Tests (React)
          command: npm run test-ci
          working_directory: src/implementations/react
  validate:
    <<: *defaults
    steps:
      - checkout
      # Get React node_modules for this revision of react/package.json
      - restore_cache:
          key: dependency-cache-react-v1-{{ checksum "src/implementations/react/package.json" }}
      - run:
          name: Validate hig-react version
          command: npm run validate
          working_directory: src/implementations/react
  deploy:
    <<: *defaults
    steps:
      - checkout
      # Get vanilla node_modules for this revision of vanilla/package.json
      - restore_cache:
          key: dependency-cache-vanilla-v1-{{ checksum "package.json" }}
      # Get React node_modules for this revision of react/package.json
      - restore_cache:
          key: dependency-cache-react-v1-{{ checksum "package.json" }}
      - run:
          name: Deploy hig-react
          command: npm publish
          working_directory: src/implementations/react
workflows:
  version: 2
  build-test-validate-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - validate:
          filters:
            branches:
              ignore: master
          requires:
            - build
            - test
      - deploy:
          #filters:
            #branches:
            #  only: master
            #tags:
            #  only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - build
            - test
