defaults: &defaults
      working_directory: ~/hig
      docker:
        - image: circleci/node:8.2.1

version: 4
jobs:
  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lerna bootstrap
          command: npm install && npm run bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - packages/vanilla/node_modules
            - packages/react/node_modules
  vanilla-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build (Vanilla)
          command: npm run lib
          working_directory: packages/vanilla
      - save_cache:
          key: lib-cache-vanilla-v5-{{ .Revision }}
          paths:
            - packages/vanilla/lib
  react-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: lib-cache-vanilla-v5-{{ .Revision }}
      - run:
          name: Build (React)
          command: npm run lib
          working_directory:  packages/react
      - save_cache:
          key: lib-cache-react-v5-{{ .Revision }}
          paths:
            - packages/react/lib
  vanilla-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: lib-cache-vanilla-v5-{{ .Revision }}
      - run:
          name: Start Server (Vanilla)
          command: ./node_modules/http-server/bin/http-server
          background: true
          working_directory: packages/vanilla
      - run:
          name: Run Tests (Vanilla)
          command: npm run gemini-ci
          working_directory: packages/vanilla
  react-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: lib-cache-vanilla-v5-{{ .Revision }}
      - restore_cache:
          key: lib-cache-react-v5-{{ .Revision }}
      - run:
          name: Run Tests (React)
          command: npm run test-ci
          working_directory: packages/react
  pacakges-deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: lib-cache-vanilla-v5-{{ .Revision }}
      - restore_cache:
          key: lib-cache-react-v5-{{ .Revision }}
      - run:
          name: Add auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          working_directory: packages/react
      - run:
          name: Deploy hig-react
          command: npm publish
          working_directory: packages/react
      - run:
          name: Deploy hig-vanilla
          command: npm publish
          working_directory: packages/vanilla
workflows:
  version: 2
  build-test-validate-and-deploy:
    jobs:
      - bootstrap
      - vanilla-build:
          requires:
            - bootstrap
      - react-build:
          requires:
            - vanilla-build
      - vanilla-test:
          requires:
            - vanilla-build
      - react-test:
          requires:
            - react-build
      - packages-deploy:
          requires:
            - vanilla-test
            - react-test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
