defaults: &defaults
      working_directory: ~/hig
      docker:
        - image: circleci/node:8.2.1

version: 4
jobs:
  bootstrap:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - run:
          name: Lerna bootstrap
          command: yarn && yarn bootstrap
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
          paths:
            - node_modules
            - packages/vanilla/node_modules
            - packages/react/node_modules
  vanilla-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - run:
          name: Build (Vanilla)
          command: yarn lib
          working_directory: packages/vanilla
      - save_cache:
          key: vanilla-build-{{ .Revision }}
          paths:
            - packages/vanilla/lib
  react-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - restore_cache:
          key: vanilla-build-{{ .Revision }}
      - run:
          name: Build (React)
          command: yarn lib
          working_directory:  packages/react
      - save_cache:
          key: react-build-{{ .Revision }}
          paths:
            - packages/react/lib
  vanilla-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - restore_cache:
          key: vanilla-build-{{ .Revision }}
      - run:
          name: Lint (Vanilla)
          command: yarn lint
          working_directory: packages/vanilla
      - run:
          name: Start Server (Vanilla)
          command: ./node_modules/http-server/bin/http-server
          background: true
          working_directory: packages/vanilla
      - run:
          name: Run Tests (Vanilla)
          command: yarn gemini-ci
          working_directory: packages/vanilla
      - store_artifacts:
          path: packages/vanilla/gemini-report
  react-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - restore_cache:
          key: vanilla-build-{{ .Revision }}
      - restore_cache:
          key: react-build-{{ .Revision }}
      - run:
          name: Lint (React)
          command: yarn lint
          working_directory: packages/react
      - run:
          name: Run Tests (React)
          command: yarn test-ci
          working_directory: packages/react
      - store_artifacts:
            path: packages/react/coverage
  packages-deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}-{{ checksum "packages/react/yarn.lock" }}-{{ checksum "packages/vanilla/yarn.lock" }}
      - restore_cache:
          key: vanilla-build-{{ .Revision }}
      - restore_cache:
          key: react-build-{{ .Revision }}
      - run:
          name: Add auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Deploy hig-react
          command: node ./scripts/publish-if-needed/index.js react
      - run:
          name: Deploy hig-interface
          command: node ./scripts/publish-if-needed/index.js interface
      - run:
          name: Deploy hig-vanilla
          command: node ./scripts/publish-if-needed/index.js vanilla
workflows:
  version: 2
  build-test-validate-and-deploy:
    jobs:
      - bootstrap
      - vanilla-build:
          requires:
            - bootstrap
      - react-build:
          requires:
            - vanilla-build
      - vanilla-test:
          requires:
            - vanilla-build
      - react-test:
          requires:
            - react-build
      - packages-deploy:
          requires:
            - vanilla-test
            - react-test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
